# Generated by Django 3.2.11 on 2023-05-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Make Up', 'Make Up'), ('Last News', 'Last News'), ('Learning', 'Learning'), ('Photo Graphy', 'Photo Graphy')], default='unknown', max_length=20),
        ),
    ]
